---
- hosts:
    - main

  vars: 
    packages:
      - git
      - default-jdk
      - maven
      - mysql-server-5.7
      - python-mysqldb
      - python-pip
      - python3-lxml

    pippackages:
      - python-jenkins
      - lxml

    host_path: /Users/akshitpatel/Desktop/School/CSC519/Milestone1/

  tasks: 
    - name: Install packages
      become: yes
      apt: 
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ packages }}"

    - name: Install remaining packages
      become: yes
      pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ pippackages }}"

- hosts: main

  vars:
    mysql_user: jenkins
    mysql_password: "{{ lookup('env','MYSQL_PASS') }}"
    email_username: aapatel8@ncsu.edu
    email_password:

  tasks:
    - name: Add id_rsa
      copy:
        src: keys/id_rsa
        dest: /var/lib/jenkins/.ssh/
        mode: 0600
        owner: jenkins

    - name: Create target directory
      file: 
        path: /var/lib/jenkins/workspace/templates
        state: directory
        mode: 0755
        owner: jenkins

    - name: Add hibernate.properties
      template:
        src: templates/hibernate.properties.template
        dest: /var/lib/jenkins/workspace/templates/hibernate.properties
        # dest: /root/iTrust2-v2-fork/iTrust2/src/main/resources/hibernate.properties
        mode: 0644
        owner: jenkins

    - name: setup db.properties
      template:
        src: templates/db.properties.template
        dest: /var/lib/jenkins/workspace/templates/db.properties
        # dest: /root/iTrust2-v2-fork/iTrust2/src/main/java/db.properties
        mode: 0644
        owner: jenkins

    - name: setup email.properties
      template:
        src: templates/email.properties.template
        dest: /var/lib/jenkins/workspace/templates/email.properties
        # dest: /root/iTrust2-v2-fork/iTrust2/src/main/java/email.properties
        mode: 0644
        owner: jenkins

    - name: Add my.cnf for mysql
      template:
        src: templates/my.cnf
        dest: /var/lib/jenkins/workspace/templates/.my.cnf
        # dest: /root/.my.cnf
        mode: 0644
        # owner: jenkins

    - name: Add mysql user
      mysql_user:
        name: root
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        login_user: root
        login_password: "{{ mysql_password }}"
        state: present
      become: yes

    - name: Update root
      raw: mysql -e "UPDATE mysql.user SET Grant_priv='Y', Super_priv='Y' WHERE User='root'; FLUSH PRIVILEGES";

    - name: Add mysql user
      mysql_user:
        name: jenkins
        password: "{{ mysql_password }}"
        priv: '*.*:ALL'
        state: present
      become: yes

    - name: Add jenkins job (iTrust2)
      jenkins_job:
        config: "{{ lookup('file', 'iTrust2.xml') }}"
        name: iTrust2
        password: 4500274d434c4307a3b864806223b577
        url: http://localhost:8080/
        user: admin
