---
- hosts: iTrust
  vars:
    itrust_home_dir: /root
    itrust_clone_dir: /root/iTrust2-v2-fork
    itrust_dir: /root/iTrust2-v2-fork/iTrust2
    mysql_user: root
    mysql_password: "{{ lookup('env','MYSQL_PASSWORD') }}"
    email_username: scbutle2@ncsu.edu
    email_password: 
    packages: 
      - git
      - mysql-server-5.7
      - openjdk-8-jdk
      - maven
      - python-mysqldb

  tasks:
  - name: install itrust dependencies
    become: yes
    apt:
      pkg: "{{ item }}"
      state: present
      #update_cache: yes
    with_items: "{{ packages }}"
        
  - name: download itrust
    git:
      repo: https://github.com/sbutler2901/iTrust2-v2-fork
      dest: "{{ itrust_clone_dir }}"
      accept_hostkey: yes
      clone: yes
      update: yes
      force: yes
 
  - name: setup itrust hibernate.properties
    template:
      src: templates/hibernate.properties.template
      dest: /root/iTrust2-v2-fork/iTrust2/src/main/resources/hibernate.properties
      owner: root
      mode: 0600 
  
  - name: setup db.properties
    template:
      src: templates/db.properties.template
      dest: /root/iTrust2-v2-fork/iTrust2/src/main/java/db.properties
      owner: root
      mode: 0600 
 
  - name: setup email.properties
    template:
      src: templates/email.properties.template
      dest: /root/iTrust2-v2-fork/iTrust2/src/main/java/email.properties
      owner: root
      mode: 0600 
  
  - name: setup mysql my.cnf
    template:
      src: templates/my.cnf
      dest: /root/.my.cnf
      owner: root
      mode: 0600 

  - name: Add mysql privileged user
    become: yes
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: '*.*:ALL'
      state: present 

  - name: restart mysql reloading configs
    become: yes
    systemd:
      state: restarted
      daemon_reload: yes
      name: mysql

  - name: maven build DB
    command: mvn -f "{{ itrust_dir }}"/pom.xml process-test-classes
  
    #- name: maven build & start itrust
    #command: mvn -f "{{ itrust_dir }}"/pom.xml jetty:run
  - name: maven build & start itrust
    command: mvn -f "{{ itrust_dir }}"/pom.xml clean test verify checkstyle:checkstyle

