---
- hosts: Checkbox

  gather_facts: no

  vars:
    MONGO_USER: "{{ lookup('env','MONGO_USER') }}"
    MONGO_PASSWORD: "{{ lookup('env','MONGO_PASSWORD') }}"
    MAIL_USER: "{{ lookup('env','MAIL_USER') }}"
    MAIL_PASSWORD: "{{ lookup('env','MAIL_PASSWORD') }}"
    MAIL_SMTP: "{{ lookup('env','MAIL_SMTP') }}"
  
  tasks:
      # Install python to use ansible
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      # Restart the server to set environment variables
    - name: Restarting Server
      become: yes
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
      async: 1
      poll: 0
      # Wait for server to reboot
    - name: Wait for reboot
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=10 state=started
      become: false
      # Install git
    - name: install git
      apt: pkg=git state=present update_cache=yes
      become: yes
      # Get nodejs package
    - name: get nodejs package
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      # Install nodejs and npm
    - name: install nodejs and npm
      apt: pkg=nodejs state=present
      # Install nginx
    - name: install nginx
      apt: pkg=nginx state=installed update_cache=true
      # Import mongodb public key (It is the first step of installing mongodb)
    - name: import mongodb public KEY
      apt_key: id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5  keyserver=keyserver.ubuntu.com
      # Create a list file for mongodb (It is the second step of installing mongodb)
    - name: create a list file for mongodb
      apt_repository: repo='deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse' state=present
      # Update apt-get to have mongodb package
    - name: update apt-get
      become: yes
      apt: update_cache=yes
      # Install mongodb (It is the last step of installing mongodb)
    - name: install mongodb
      apt: pkg=mongodb-org state=present force=yes
      # Start mongodb service
    - name: start mongodb service
      shell: service mongod start
      become: yes
      # Install python setuptools to install pymongo using this
    - name: install python setuptools
      apt: pkg=python-setuptools state=present
      become: yes
      # Install pymongo, It is necessary when we want to create mongodb user
    - name: install pymongo
      shell: python -m easy_install pymongo
      become: yes
      # Create an admin user for mongodb
    - name: create mongodb admin user
      mongodb_user:
        database: admin
        name: "{{MONGO_USER}}"
        password: "{{MONGO_PASSWORD}}"
        roles:
          - { db: "admin", role: "readWrite" }
          - { db: "admin", role: "dbAdmin" }
          - { db: "admin", role: "userAdmin" }
        login_port: 27017
        state: present
      # Clone the checkbox.io repository
    - name: clone checkbox.io repository
      become: yes
      git:
        repo: https://github.com/chrisparnin/checkbox.io
        dest: ./checkbox
      # Install checkbox.io packages
    - name: install checkbox packages
      shell: npm install
      args:
        chdir: ./checkbox/server-side/site
      # Changing permission of the /root/checkbox/public_html to make it executable
    - name: Changing permission of "/root", adding "+x"
      file: dest=/root/ mode=+x
    - name: Changing permission of "/root/checkbox", adding "+x"
      file: dest=/root/checkbox mode=+x
    - name: Changing permission of "/root/checkbox/public_html", adding "+x"
      file: dest=/root/checkbox/public_html mode=+x
      # Add default file to /etc/nginx/sites-available using template
    - name: Add default file to nginx
      template: src=/var/lib/jenkins/workspace/templates/default dest=/etc/nginx/sites-available/default
      become: yes
      # Add nginx.config file to /etc/nginx using template
    - name: Add nginx.config file to nginx
      template: src=/var/lib/jenkins/workspace/templates/nginx.config dest=/etc/nginx/nginx.conf
      become: yes
      # Reload nginx to apply new configuration
    - name: reload nginx
      shell: nginx -s reload
      become: yes
      # Install forever to manage running application
    - name: install forever
      npm: name=forever global=yes state=present
      # Run the checkbox.io using forever
    - name: run checkbox
      shell: forever start server.js
      args:
        chdir: ./checkbox/server-side/site/
...
